//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53AffectedRecordSet) DeepCopyInto(out *Route53AffectedRecordSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53AffectedRecordSet.
func (in *Route53AffectedRecordSet) DeepCopy() *Route53AffectedRecordSet {
	if in == nil {
		return nil
	}
	out := new(Route53AffectedRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53AliasTarget) DeepCopyInto(out *Route53AliasTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53AliasTarget.
func (in *Route53AliasTarget) DeepCopy() *Route53AliasTarget {
	if in == nil {
		return nil
	}
	out := new(Route53AliasTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53AssumeRole) DeepCopyInto(out *Route53AssumeRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53AssumeRole.
func (in *Route53AssumeRole) DeepCopy() *Route53AssumeRole {
	if in == nil {
		return nil
	}
	out := new(Route53AssumeRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53Change) DeepCopyInto(out *Route53Change) {
	*out = *in
	in.SubmittedAt.DeepCopyInto(&out.SubmittedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53Change.
func (in *Route53Change) DeepCopy() *Route53Change {
	if in == nil {
		return nil
	}
	out := new(Route53Change)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53Credentials) DeepCopyInto(out *Route53Credentials) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(Route53RuntimeCredentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53Credentials.
func (in *Route53Credentials) DeepCopy() *Route53Credentials {
	if in == nil {
		return nil
	}
	out := new(Route53Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53Identity) DeepCopyInto(out *Route53Identity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53Identity.
func (in *Route53Identity) DeepCopy() *Route53Identity {
	if in == nil {
		return nil
	}
	out := new(Route53Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Route53Identity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53IdentityList) DeepCopyInto(out *Route53IdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Route53Identity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53IdentityList.
func (in *Route53IdentityList) DeepCopy() *Route53IdentityList {
	if in == nil {
		return nil
	}
	out := new(Route53IdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Route53IdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53IdentitySpec) DeepCopyInto(out *Route53IdentitySpec) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.AssumeRoleChain != nil {
		in, out := &in.AssumeRoleChain, &out.AssumeRoleChain
		*out = make([]Route53AssumeRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53IdentitySpec.
func (in *Route53IdentitySpec) DeepCopy() *Route53IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(Route53IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53IdentityStatus) DeepCopyInto(out *Route53IdentityStatus) {
	*out = *in
	if in.LastCredentialCheckTime != nil {
		in, out := &in.LastCredentialCheckTime, &out.LastCredentialCheckTime
		*out = (*in).DeepCopy()
	}
	if in.NextCredentialCheckTime != nil {
		in, out := &in.NextCredentialCheckTime, &out.NextCredentialCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53IdentityStatus.
func (in *Route53IdentityStatus) DeepCopy() *Route53IdentityStatus {
	if in == nil {
		return nil
	}
	out := new(Route53IdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53PendingChange) DeepCopyInto(out *Route53PendingChange) {
	*out = *in
	in.SubmittedAt.DeepCopyInto(&out.SubmittedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53PendingChange.
func (in *Route53PendingChange) DeepCopy() *Route53PendingChange {
	if in == nil {
		return nil
	}
	out := new(Route53PendingChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53PendingRecordSetChange) DeepCopyInto(out *Route53PendingRecordSetChange) {
	*out = *in
	in.SubmittedAt.DeepCopyInto(&out.SubmittedAt)
	if in.AffectedRecordSets != nil {
		in, out := &in.AffectedRecordSets, &out.AffectedRecordSets
		*out = make([]Route53AffectedRecordSet, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53PendingRecordSetChange.
func (in *Route53PendingRecordSetChange) DeepCopy() *Route53PendingRecordSetChange {
	if in == nil {
		return nil
	}
	out := new(Route53PendingRecordSetChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53RecordSetOptions) DeepCopyInto(out *Route53RecordSetOptions) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(Route53AliasTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53RecordSetOptions.
func (in *Route53RecordSetOptions) DeepCopy() *Route53RecordSetOptions {
	if in == nil {
		return nil
	}
	out := new(Route53RecordSetOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53RecordSetStatusData) DeepCopyInto(out *Route53RecordSetStatusData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53RecordSetStatusData.
func (in *Route53RecordSetStatusData) DeepCopy() *Route53RecordSetStatusData {
	if in == nil {
		return nil
	}
	out := new(Route53RecordSetStatusData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53RuntimeCredentials) DeepCopyInto(out *Route53RuntimeCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53RuntimeCredentials.
func (in *Route53RuntimeCredentials) DeepCopy() *Route53RuntimeCredentials {
	if in == nil {
		return nil
	}
	out := new(Route53RuntimeCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ZoneClassParameters) DeepCopyInto(out *Route53ZoneClassParameters) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ZoneClassParameters.
func (in *Route53ZoneClassParameters) DeepCopy() *Route53ZoneClassParameters {
	if in == nil {
		return nil
	}
	out := new(Route53ZoneClassParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53ZoneStatusData) DeepCopyInto(out *Route53ZoneStatusData) {
	*out = *in
	if in.PendingHostedZoneChange != nil {
		in, out := &in.PendingHostedZoneChange, &out.PendingHostedZoneChange
		*out = new(Route53PendingChange)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingRecordSetChange != nil {
		in, out := &in.PendingRecordSetChange, &out.PendingRecordSetChange
		*out = new(Route53PendingRecordSetChange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53ZoneStatusData.
func (in *Route53ZoneStatusData) DeepCopy() *Route53ZoneStatusData {
	if in == nil {
		return nil
	}
	out := new(Route53ZoneStatusData)
	in.DeepCopyInto(out)
	return out
}
