resources:
  - bases/dns.appthrust.io_providers.yaml
  - bases/dns.appthrust.io_zoneclasses.yaml
  - bases/dns.appthrust.io_zones.yaml
  - bases/dns.appthrust.io_recordsets.yaml
  - bases/dns.appthrust.io_zoneunits.yaml
  - bases/cloudflare.dns.appthrust.io_cloudflareidentities.yaml
  - bases/route53.dns.appthrust.io_route53identities.yaml
