{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dns-api.fullname" . }}-controller-manager-role
  labels:
    {{- include "dns-api.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - services/finalizers
    verbs:
      - update
  - apiGroups:
      - cloudflare.dns.appthrust.io
    resources:
      - cloudflareidentities
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudflare.dns.appthrust.io
    resources:
      - cloudflareidentities/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - dns.appthrust.io
    resources:
      - providers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dns.appthrust.io
    resources:
      - recordsets
      - zoneunits
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dns.appthrust.io
    resources:
      - recordsets/finalizers
      - zones/finalizers
      - zoneunits/finalizers
    verbs:
      - update
  - apiGroups:
      - dns.appthrust.io
    resources:
      - recordsets/status
      - zoneclasses/status
      - zones/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - dns.appthrust.io
    resources:
      - zoneunits/status
    verbs:
      - get
      - patch
      - update
      - watch
  - apiGroups:
      - dns.appthrust.io
    resources:
      - zoneclasses
      - zones
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - endpoint.dns.appthrust.io
    resources:
      - endpointprovidercapabilities
      - endpointrecordsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - endpoint.dns.appthrust.io
    resources:
      - endpointrecordsets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - endpoint.route53.dns.appthrust.io
    resources:
      - endpointrecordsetconversions
    verbs:
      - create
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes/finalizers
    verbs:
      - update
  - apiGroups:
      - route53.dns.appthrust.io
    resources:
      - route53identities
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route53.dns.appthrust.io
    resources:
      - route53identities/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dns-api.fullname" . }}-controller-manager-rolebinding
  labels:
    {{- include "dns-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dns-api.fullname" . }}-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "dns-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
