//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessTokenSource) DeepCopyInto(out *CloudflareAccessTokenSource) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessTokenSource.
func (in *CloudflareAccessTokenSource) DeepCopy() *CloudflareAccessTokenSource {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessTokenSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessTokenStatus) DeepCopyInto(out *CloudflareAccessTokenStatus) {
	*out = *in
	if in.ExpiresOn != nil {
		in, out := &in.ExpiresOn, &out.ExpiresOn
		*out = (*in).DeepCopy()
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessTokenStatus.
func (in *CloudflareAccessTokenStatus) DeepCopy() *CloudflareAccessTokenStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccountStatus) DeepCopyInto(out *CloudflareAccountStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccountStatus.
func (in *CloudflareAccountStatus) DeepCopy() *CloudflareAccountStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecordState) DeepCopyInto(out *CloudflareDNSRecordState) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
	if in.Proxiable != nil {
		in, out := &in.Proxiable, &out.Proxiable
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecordState.
func (in *CloudflareDNSRecordState) DeepCopy() *CloudflareDNSRecordState {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecordState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecordStatus) DeepCopyInto(out *CloudflareDNSRecordStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecordStatus.
func (in *CloudflareDNSRecordStatus) DeepCopy() *CloudflareDNSRecordStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareIdentity) DeepCopyInto(out *CloudflareIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareIdentity.
func (in *CloudflareIdentity) DeepCopy() *CloudflareIdentity {
	if in == nil {
		return nil
	}
	out := new(CloudflareIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareIdentityList) DeepCopyInto(out *CloudflareIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareIdentityList.
func (in *CloudflareIdentityList) DeepCopy() *CloudflareIdentityList {
	if in == nil {
		return nil
	}
	out := new(CloudflareIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareIdentitySpec) DeepCopyInto(out *CloudflareIdentitySpec) {
	*out = *in
	out.AccessToken = in.AccessToken
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareIdentitySpec.
func (in *CloudflareIdentitySpec) DeepCopy() *CloudflareIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareIdentityStatus) DeepCopyInto(out *CloudflareIdentityStatus) {
	*out = *in
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(CloudflareAccountStatus)
		**out = **in
	}
	if in.AccessToken != nil {
		in, out := &in.AccessToken, &out.AccessToken
		*out = new(CloudflareAccessTokenStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCredentialCheckTime != nil {
		in, out := &in.LastCredentialCheckTime, &out.LastCredentialCheckTime
		*out = (*in).DeepCopy()
	}
	if in.NextCredentialCheckTime != nil {
		in, out := &in.NextCredentialCheckTime, &out.NextCredentialCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareIdentityStatus.
func (in *CloudflareIdentityStatus) DeepCopy() *CloudflareIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRecordSetAdoption) DeepCopyInto(out *CloudflareRecordSetAdoption) {
	*out = *in
	if in.RecordIDs != nil {
		in, out := &in.RecordIDs, &out.RecordIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRecordSetAdoption.
func (in *CloudflareRecordSetAdoption) DeepCopy() *CloudflareRecordSetAdoption {
	if in == nil {
		return nil
	}
	out := new(CloudflareRecordSetAdoption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRecordSetOptions) DeepCopyInto(out *CloudflareRecordSetOptions) {
	*out = *in
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRecordSetOptions.
func (in *CloudflareRecordSetOptions) DeepCopy() *CloudflareRecordSetOptions {
	if in == nil {
		return nil
	}
	out := new(CloudflareRecordSetOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRecordSetState) DeepCopyInto(out *CloudflareRecordSetState) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]CloudflareDNSRecordState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRecordSetState.
func (in *CloudflareRecordSetState) DeepCopy() *CloudflareRecordSetState {
	if in == nil {
		return nil
	}
	out := new(CloudflareRecordSetState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRecordSetStatusData) DeepCopyInto(out *CloudflareRecordSetStatusData) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]CloudflareDNSRecordStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRecordSetStatusData.
func (in *CloudflareRecordSetStatusData) DeepCopy() *CloudflareRecordSetStatusData {
	if in == nil {
		return nil
	}
	out := new(CloudflareRecordSetStatusData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareSecretKeyReference) DeepCopyInto(out *CloudflareSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareSecretKeyReference.
func (in *CloudflareSecretKeyReference) DeepCopy() *CloudflareSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(CloudflareSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneAdoption) DeepCopyInto(out *CloudflareZoneAdoption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneAdoption.
func (in *CloudflareZoneAdoption) DeepCopy() *CloudflareZoneAdoption {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneAdoption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneClassParameters) DeepCopyInto(out *CloudflareZoneClassParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneClassParameters.
func (in *CloudflareZoneClassParameters) DeepCopy() *CloudflareZoneClassParameters {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneClassParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneCreationIntent) DeepCopyInto(out *CloudflareZoneCreationIntent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneCreationIntent.
func (in *CloudflareZoneCreationIntent) DeepCopy() *CloudflareZoneCreationIntent {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneCreationIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneState) DeepCopyInto(out *CloudflareZoneState) {
	*out = *in
	if in.CreationIntent != nil {
		in, out := &in.CreationIntent, &out.CreationIntent
		*out = new(CloudflareZoneCreationIntent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneState.
func (in *CloudflareZoneState) DeepCopy() *CloudflareZoneState {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneStatus) DeepCopyInto(out *CloudflareZoneStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneStatus.
func (in *CloudflareZoneStatus) DeepCopy() *CloudflareZoneStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneStatusData) DeepCopyInto(out *CloudflareZoneStatusData) {
	*out = *in
	out.Zone = in.Zone
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneStatusData.
func (in *CloudflareZoneStatusData) DeepCopy() *CloudflareZoneStatusData {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneStatusData)
	in.DeepCopyInto(out)
	return out
}
