//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AAAARecordSet) DeepCopyInto(out *AAAARecordSet) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AAAARecordSet.
func (in *AAAARecordSet) DeepCopy() *AAAARecordSet {
	if in == nil {
		return nil
	}
	out := new(AAAARecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ARecordSet) DeepCopyInto(out *ARecordSet) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ARecordSet.
func (in *ARecordSet) DeepCopy() *ARecordSet {
	if in == nil {
		return nil
	}
	out := new(ARecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRecord) DeepCopyInto(out *AllowedRecord) {
	*out = *in
	out.Name = in.Name
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]RecordType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRecord.
func (in *AllowedRecord) DeepCopy() *AllowedRecord {
	if in == nil {
		return nil
	}
	out := new(AllowedRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRecordSet) DeepCopyInto(out *AllowedRecordSet) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]AllowedRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRecordSet.
func (in *AllowedRecordSet) DeepCopy() *AllowedRecordSet {
	if in == nil {
		return nil
	}
	out := new(AllowedRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedRecordSetNamespaces) DeepCopyInto(out *AllowedRecordSetNamespaces) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedRecordSetNamespaces.
func (in *AllowedRecordSetNamespaces) DeepCopy() *AllowedRecordSetNamespaces {
	if in == nil {
		return nil
	}
	out := new(AllowedRecordSetNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAARecord) DeepCopyInto(out *CAARecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAARecord.
func (in *CAARecord) DeepCopy() *CAARecord {
	if in == nil {
		return nil
	}
	out := new(CAARecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAARecordSet) DeepCopyInto(out *CAARecordSet) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]CAARecord, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAARecordSet.
func (in *CAARecordSet) DeepCopy() *CAARecordSet {
	if in == nil {
		return nil
	}
	out := new(CAARecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordSet) DeepCopyInto(out *CNAMERecordSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordSet.
func (in *CNAMERecordSet) DeepCopy() *CNAMERecordSet {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecord) DeepCopyInto(out *MXRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecord.
func (in *MXRecord) DeepCopy() *MXRecord {
	if in == nil {
		return nil
	}
	out := new(MXRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordSet) DeepCopyInto(out *MXRecordSet) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]MXRecord, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordSet.
func (in *MXRecordSet) DeepCopy() *MXRecordSet {
	if in == nil {
		return nil
	}
	out := new(MXRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NSRecordSet) DeepCopyInto(out *NSRecordSet) {
	*out = *in
	if in.NameServers != nil {
		in, out := &in.NameServers, &out.NameServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NSRecordSet.
func (in *NSRecordSet) DeepCopy() *NSRecordSet {
	if in == nil {
		return nil
	}
	out := new(NSRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacePolicy) DeepCopyInto(out *NamespacePolicy) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacePolicy.
func (in *NamespacePolicy) DeepCopy() *NamespacePolicy {
	if in == nil {
		return nil
	}
	out := new(NamespacePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConditionReason) DeepCopyInto(out *ProviderConditionReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConditionReason.
func (in *ProviderConditionReason) DeepCopy() *ProviderConditionReason {
	if in == nil {
		return nil
	}
	out := new(ProviderConditionReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConversion) DeepCopyInto(out *ProviderConversion) {
	*out = *in
	in.ToStorage.DeepCopyInto(&out.ToStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConversion.
func (in *ProviderConversion) DeepCopy() *ProviderConversion {
	if in == nil {
		return nil
	}
	out := new(ProviderConversion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConversionTarget) DeepCopyInto(out *ProviderConversionTarget) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(ProviderConversionWebhook)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConversionTarget.
func (in *ProviderConversionTarget) DeepCopy() *ProviderConversionTarget {
	if in == nil {
		return nil
	}
	out := new(ProviderConversionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConversionWebhook) DeepCopyInto(out *ProviderConversionWebhook) {
	*out = *in
	in.ClientConfig.DeepCopyInto(&out.ClientConfig)
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConversionWebhook.
func (in *ProviderConversionWebhook) DeepCopy() *ProviderConversionWebhook {
	if in == nil {
		return nil
	}
	out := new(ProviderConversionWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConversionWebhookClientConfig) DeepCopyInto(out *ProviderConversionWebhookClientConfig) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConversionWebhookClientConfig.
func (in *ProviderConversionWebhookClientConfig) DeepCopy() *ProviderConversionWebhookClientConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConversionWebhookClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConversionWebhookServiceReference) DeepCopyInto(out *ProviderConversionWebhookServiceReference) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConversionWebhookServiceReference.
func (in *ProviderConversionWebhookServiceReference) DeepCopy() *ProviderConversionWebhookServiceReference {
	if in == nil {
		return nil
	}
	out := new(ProviderConversionWebhookServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderDisplay) DeepCopyInto(out *ProviderDisplay) {
	*out = *in
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(ProviderLogo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderDisplay.
func (in *ProviderDisplay) DeepCopy() *ProviderDisplay {
	if in == nil {
		return nil
	}
	out := new(ProviderDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderIdentity) DeepCopyInto(out *ProviderIdentity) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderIdentity.
func (in *ProviderIdentity) DeepCopy() *ProviderIdentity {
	if in == nil {
		return nil
	}
	out := new(ProviderIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderIdentityResource) DeepCopyInto(out *ProviderIdentityResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderIdentityResource.
func (in *ProviderIdentityResource) DeepCopy() *ProviderIdentityResource {
	if in == nil {
		return nil
	}
	out := new(ProviderIdentityResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderLogo) DeepCopyInto(out *ProviderLogo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderLogo.
func (in *ProviderLogo) DeepCopy() *ProviderLogo {
	if in == nil {
		return nil
	}
	out := new(ProviderLogo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderOpenAPISchema) DeepCopyInto(out *ProviderOpenAPISchema) {
	*out = *in
	in.OpenAPIV3Schema.DeepCopyInto(&out.OpenAPIV3Schema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderOpenAPISchema.
func (in *ProviderOpenAPISchema) DeepCopy() *ProviderOpenAPISchema {
	if in == nil {
		return nil
	}
	out := new(ProviderOpenAPISchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRecordSet) DeepCopyInto(out *ProviderRecordSet) {
	*out = *in
	if in.SupportedTypes != nil {
		in, out := &in.SupportedTypes, &out.SupportedTypes
		*out = make([]RecordType, len(*in))
		copy(*out, *in)
	}
	in.Schemas.DeepCopyInto(&out.Schemas)
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]ProviderValidationRule, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalConditionReasons != nil {
		in, out := &in.AdditionalConditionReasons, &out.AdditionalConditionReasons
		*out = make([]ProviderConditionReason, len(*in))
		copy(*out, *in)
	}
	if in.DisableValidations != nil {
		in, out := &in.DisableValidations, &out.DisableValidations
		*out = make([]RecordSetValidationToggle, len(*in))
		copy(*out, *in)
	}
	in.Conversion.DeepCopyInto(&out.Conversion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRecordSet.
func (in *ProviderRecordSet) DeepCopy() *ProviderRecordSet {
	if in == nil {
		return nil
	}
	out := new(ProviderRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRecordSetSchemas) DeepCopyInto(out *ProviderRecordSetSchemas) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
	if in.Adoption != nil {
		in, out := &in.Adoption, &out.Adoption
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusProviderData != nil {
		in, out := &in.StatusProviderData, &out.StatusProviderData
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRecordSetSchemas.
func (in *ProviderRecordSetSchemas) DeepCopy() *ProviderRecordSetSchemas {
	if in == nil {
		return nil
	}
	out := new(ProviderRecordSetSchemas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReference) DeepCopyInto(out *ProviderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReference.
func (in *ProviderReference) DeepCopy() *ProviderReference {
	if in == nil {
		return nil
	}
	out := new(ProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.Display.DeepCopyInto(&out.Display)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ProviderVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidationRule) DeepCopyInto(out *ProviderValidationRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidationRule.
func (in *ProviderValidationRule) DeepCopy() *ProviderValidationRule {
	if in == nil {
		return nil
	}
	out := new(ProviderValidationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersion) DeepCopyInto(out *ProviderVersion) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(ProviderIdentity)
		**out = **in
	}
	in.ZoneClass.DeepCopyInto(&out.ZoneClass)
	in.Zone.DeepCopyInto(&out.Zone)
	in.RecordSet.DeepCopyInto(&out.RecordSet)
	in.ZoneUnit.DeepCopyInto(&out.ZoneUnit)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersion.
func (in *ProviderVersion) DeepCopy() *ProviderVersion {
	if in == nil {
		return nil
	}
	out := new(ProviderVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderZone) DeepCopyInto(out *ProviderZone) {
	*out = *in
	in.Schemas.DeepCopyInto(&out.Schemas)
	if in.AdditionalConditionReasons != nil {
		in, out := &in.AdditionalConditionReasons, &out.AdditionalConditionReasons
		*out = make([]ProviderConditionReason, len(*in))
		copy(*out, *in)
	}
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]ProviderValidationRule, len(*in))
		copy(*out, *in)
	}
	in.Conversion.DeepCopyInto(&out.Conversion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderZone.
func (in *ProviderZone) DeepCopy() *ProviderZone {
	if in == nil {
		return nil
	}
	out := new(ProviderZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderZoneClass) DeepCopyInto(out *ProviderZoneClass) {
	*out = *in
	in.Schemas.DeepCopyInto(&out.Schemas)
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]ProviderValidationRule, len(*in))
		copy(*out, *in)
	}
	in.Conversion.DeepCopyInto(&out.Conversion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderZoneClass.
func (in *ProviderZoneClass) DeepCopy() *ProviderZoneClass {
	if in == nil {
		return nil
	}
	out := new(ProviderZoneClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderZoneClassSchemas) DeepCopyInto(out *ProviderZoneClassSchemas) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderZoneClassSchemas.
func (in *ProviderZoneClassSchemas) DeepCopy() *ProviderZoneClassSchemas {
	if in == nil {
		return nil
	}
	out := new(ProviderZoneClassSchemas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderZoneSchemas) DeepCopyInto(out *ProviderZoneSchemas) {
	*out = *in
	if in.Adoption != nil {
		in, out := &in.Adoption, &out.Adoption
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusProviderData != nil {
		in, out := &in.StatusProviderData, &out.StatusProviderData
		*out = new(ProviderOpenAPISchema)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderZoneSchemas.
func (in *ProviderZoneSchemas) DeepCopy() *ProviderZoneSchemas {
	if in == nil {
		return nil
	}
	out := new(ProviderZoneSchemas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderZoneUnit) DeepCopyInto(out *ProviderZoneUnit) {
	*out = *in
	if in.DisableValidations != nil {
		in, out := &in.DisableValidations, &out.DisableValidations
		*out = make([]ZoneUnitValidationToggle, len(*in))
		copy(*out, *in)
	}
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]ProviderValidationRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderZoneUnit.
func (in *ProviderZoneUnit) DeepCopy() *ProviderZoneUnit {
	if in == nil {
		return nil
	}
	out := new(ProviderZoneUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordNamePolicy) DeepCopyInto(out *RecordNamePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordNamePolicy.
func (in *RecordNamePolicy) DeepCopy() *RecordNamePolicy {
	if in == nil {
		return nil
	}
	out := new(RecordNamePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSet) DeepCopyInto(out *RecordSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSet.
func (in *RecordSet) DeepCopy() *RecordSet {
	if in == nil {
		return nil
	}
	out := new(RecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetList) DeepCopyInto(out *RecordSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetList.
func (in *RecordSetList) DeepCopy() *RecordSetList {
	if in == nil {
		return nil
	}
	out := new(RecordSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetSpec) DeepCopyInto(out *RecordSetSpec) {
	*out = *in
	in.ZoneRef.DeepCopyInto(&out.ZoneRef)
	out.Provider = in.Provider
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.A != nil {
		in, out := &in.A, &out.A
		*out = new(ARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.AAAA != nil {
		in, out := &in.AAAA, &out.AAAA
		*out = new(AAAARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.TXT != nil {
		in, out := &in.TXT, &out.TXT
		*out = new(TXTRecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.CNAME != nil {
		in, out := &in.CNAME, &out.CNAME
		*out = new(CNAMERecordSet)
		**out = **in
	}
	if in.MX != nil {
		in, out := &in.MX, &out.MX
		*out = new(MXRecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.CAA != nil {
		in, out := &in.CAA, &out.CAA
		*out = new(CAARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.NS != nil {
		in, out := &in.NS, &out.NS
		*out = new(NSRecordSet)
		(*in).DeepCopyInto(*out)
	}
	in.Options.DeepCopyInto(&out.Options)
	in.Adoption.DeepCopyInto(&out.Adoption)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetSpec.
func (in *RecordSetSpec) DeepCopy() *RecordSetSpec {
	if in == nil {
		return nil
	}
	out := new(RecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetStatus) DeepCopyInto(out *RecordSetStatus) {
	*out = *in
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(RecordSetZoneStatus)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetStatus.
func (in *RecordSetStatus) DeepCopy() *RecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(RecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetValidationToggle) DeepCopyInto(out *RecordSetValidationToggle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetValidationToggle.
func (in *RecordSetValidationToggle) DeepCopy() *RecordSetValidationToggle {
	if in == nil {
		return nil
	}
	out := new(RecordSetValidationToggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetZoneStatus) DeepCopyInto(out *RecordSetZoneStatus) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetZoneStatus.
func (in *RecordSetZoneStatus) DeepCopy() *RecordSetZoneStatus {
	if in == nil {
		return nil
	}
	out := new(RecordSetZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TXTRecordSet) DeepCopyInto(out *TXTRecordSet) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TXTRecordSet.
func (in *TXTRecordSet) DeepCopy() *TXTRecordSet {
	if in == nil {
		return nil
	}
	out := new(TXTRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedLocalObjectReference) DeepCopyInto(out *TypedLocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedLocalObjectReference.
func (in *TypedLocalObjectReference) DeepCopy() *TypedLocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(TypedLocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zone.
func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Zone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClass) DeepCopyInto(out *ZoneClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClass.
func (in *ZoneClass) DeepCopy() *ZoneClass {
	if in == nil {
		return nil
	}
	out := new(ZoneClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClassAllowedZones) DeepCopyInto(out *ZoneClassAllowedZones) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClassAllowedZones.
func (in *ZoneClassAllowedZones) DeepCopy() *ZoneClassAllowedZones {
	if in == nil {
		return nil
	}
	out := new(ZoneClassAllowedZones)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClassList) DeepCopyInto(out *ZoneClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZoneClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClassList.
func (in *ZoneClassList) DeepCopy() *ZoneClassList {
	if in == nil {
		return nil
	}
	out := new(ZoneClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClassReference) DeepCopyInto(out *ZoneClassReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClassReference.
func (in *ZoneClassReference) DeepCopy() *ZoneClassReference {
	if in == nil {
		return nil
	}
	out := new(ZoneClassReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClassSpec) DeepCopyInto(out *ZoneClassSpec) {
	*out = *in
	out.Provider = in.Provider
	out.IdentityRef = in.IdentityRef
	in.Parameters.DeepCopyInto(&out.Parameters)
	in.AllowedZones.DeepCopyInto(&out.AllowedZones)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClassSpec.
func (in *ZoneClassSpec) DeepCopy() *ZoneClassSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneClassStatus) DeepCopyInto(out *ZoneClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneClassStatus.
func (in *ZoneClassStatus) DeepCopy() *ZoneClassStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneList) DeepCopyInto(out *ZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Zone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneList.
func (in *ZoneList) DeepCopy() *ZoneList {
	if in == nil {
		return nil
	}
	out := new(ZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneReference) DeepCopyInto(out *ZoneReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneReference.
func (in *ZoneReference) DeepCopy() *ZoneReference {
	if in == nil {
		return nil
	}
	out := new(ZoneReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneSpec) DeepCopyInto(out *ZoneSpec) {
	*out = *in
	in.ZoneClassRef.DeepCopyInto(&out.ZoneClassRef)
	out.Provider = in.Provider
	in.Adoption.DeepCopyInto(&out.Adoption)
	if in.AllowedRecordSets != nil {
		in, out := &in.AllowedRecordSets, &out.AllowedRecordSets
		*out = make([]AllowedRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneSpec.
func (in *ZoneSpec) DeepCopy() *ZoneSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneStatus) DeepCopyInto(out *ZoneStatus) {
	*out = *in
	if in.NameServers != nil {
		in, out := &in.NameServers, &out.NameServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneStatus.
func (in *ZoneStatus) DeepCopy() *ZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnit) DeepCopyInto(out *ZoneUnit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnit.
func (in *ZoneUnit) DeepCopy() *ZoneUnit {
	if in == nil {
		return nil
	}
	out := new(ZoneUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneUnit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitList) DeepCopyInto(out *ZoneUnitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZoneUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitList.
func (in *ZoneUnitList) DeepCopy() *ZoneUnitList {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneUnitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitRecordSetSpec) DeepCopyInto(out *ZoneUnitRecordSetSpec) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.A != nil {
		in, out := &in.A, &out.A
		*out = new(ARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.AAAA != nil {
		in, out := &in.AAAA, &out.AAAA
		*out = new(AAAARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.TXT != nil {
		in, out := &in.TXT, &out.TXT
		*out = new(TXTRecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.CNAME != nil {
		in, out := &in.CNAME, &out.CNAME
		*out = new(CNAMERecordSet)
		**out = **in
	}
	if in.MX != nil {
		in, out := &in.MX, &out.MX
		*out = new(MXRecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.CAA != nil {
		in, out := &in.CAA, &out.CAA
		*out = new(CAARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.NS != nil {
		in, out := &in.NS, &out.NS
		*out = new(NSRecordSet)
		(*in).DeepCopyInto(*out)
	}
	in.Options.DeepCopyInto(&out.Options)
	in.Adoption.DeepCopyInto(&out.Adoption)
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitRecordSetSpec.
func (in *ZoneUnitRecordSetSpec) DeepCopy() *ZoneUnitRecordSetSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitRecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitRecordSetStatus) DeepCopyInto(out *ZoneUnitRecordSetStatus) {
	*out = *in
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitRecordSetStatus.
func (in *ZoneUnitRecordSetStatus) DeepCopy() *ZoneUnitRecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitRecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitSpec) DeepCopyInto(out *ZoneUnitSpec) {
	*out = *in
	out.Provider = in.Provider
	in.Zone.DeepCopyInto(&out.Zone)
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]ZoneUnitRecordSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitSpec.
func (in *ZoneUnitSpec) DeepCopy() *ZoneUnitSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitStatus) DeepCopyInto(out *ZoneUnitStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(ZoneUnitZoneStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]ZoneUnitRecordSetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitStatus.
func (in *ZoneUnitStatus) DeepCopy() *ZoneUnitStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitValidationToggle) DeepCopyInto(out *ZoneUnitValidationToggle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitValidationToggle.
func (in *ZoneUnitValidationToggle) DeepCopy() *ZoneUnitValidationToggle {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitValidationToggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitZoneSpec) DeepCopyInto(out *ZoneUnitZoneSpec) {
	*out = *in
	out.Ref = in.Ref
	out.ZoneClassRef = in.ZoneClassRef
	in.Adoption.DeepCopyInto(&out.Adoption)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitZoneSpec.
func (in *ZoneUnitZoneSpec) DeepCopy() *ZoneUnitZoneSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUnitZoneStatus) DeepCopyInto(out *ZoneUnitZoneStatus) {
	*out = *in
	if in.NameServers != nil {
		in, out := &in.NameServers, &out.NameServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUnitZoneStatus.
func (in *ZoneUnitZoneStatus) DeepCopy() *ZoneUnitZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneUnitZoneStatus)
	in.DeepCopyInto(out)
	return out
}
