//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	endpointv1alpha1 "github.com/appthrust/dns-api/pkg/go/api/endpoint/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversion) DeepCopyInto(out *EndpointRecordSetConversion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversion.
func (in *EndpointRecordSetConversion) DeepCopy() *EndpointRecordSetConversion {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointRecordSetConversion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionList) DeepCopyInto(out *EndpointRecordSetConversionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointRecordSetConversion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionList.
func (in *EndpointRecordSetConversionList) DeepCopy() *EndpointRecordSetConversionList {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointRecordSetConversionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionResult) DeepCopyInto(out *EndpointRecordSetConversionResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionResult.
func (in *EndpointRecordSetConversionResult) DeepCopy() *EndpointRecordSetConversionResult {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionSpec) DeepCopyInto(out *EndpointRecordSetConversionSpec) {
	*out = *in
	in.Input.DeepCopyInto(&out.Input)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionSpec.
func (in *EndpointRecordSetConversionSpec) DeepCopy() *EndpointRecordSetConversionSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionStatus) DeepCopyInto(out *EndpointRecordSetConversionStatus) {
	*out = *in
	out.Result = in.Result
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(endpointv1alpha1.EndpointRecordSetConversionOutput)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionStatus.
func (in *EndpointRecordSetConversionStatus) DeepCopy() *EndpointRecordSetConversionStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionStatus)
	in.DeepCopyInto(out)
	return out
}
