//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	dnsv1alpha1 "github.com/appthrust/dns-api/pkg/go/api/dns/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointProviderCapability) DeepCopyInto(out *EndpointProviderCapability) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointProviderCapability.
func (in *EndpointProviderCapability) DeepCopy() *EndpointProviderCapability {
	if in == nil {
		return nil
	}
	out := new(EndpointProviderCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointProviderCapability) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointProviderCapabilityList) DeepCopyInto(out *EndpointProviderCapabilityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointProviderCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointProviderCapabilityList.
func (in *EndpointProviderCapabilityList) DeepCopy() *EndpointProviderCapabilityList {
	if in == nil {
		return nil
	}
	out := new(EndpointProviderCapabilityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointProviderCapabilityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointProviderCapabilitySpec) DeepCopyInto(out *EndpointProviderCapabilitySpec) {
	*out = *in
	out.Provider = in.Provider
	out.Conversion = in.Conversion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointProviderCapabilitySpec.
func (in *EndpointProviderCapabilitySpec) DeepCopy() *EndpointProviderCapabilitySpec {
	if in == nil {
		return nil
	}
	out := new(EndpointProviderCapabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSet) DeepCopyInto(out *EndpointRecordSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSet.
func (in *EndpointRecordSet) DeepCopy() *EndpointRecordSet {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointRecordSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionAPI) DeepCopyInto(out *EndpointRecordSetConversionAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionAPI.
func (in *EndpointRecordSetConversionAPI) DeepCopy() *EndpointRecordSetConversionAPI {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionInput) DeepCopyInto(out *EndpointRecordSetConversionInput) {
	*out = *in
	out.Zone = in.Zone
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]EndpointTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionInput.
func (in *EndpointRecordSetConversionInput) DeepCopy() *EndpointRecordSetConversionInput {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionOutput) DeepCopyInto(out *EndpointRecordSetConversionOutput) {
	*out = *in
	if in.Fragments != nil {
		in, out := &in.Fragments, &out.Fragments
		*out = make([]RecordSetSpecFragment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionOutput.
func (in *EndpointRecordSetConversionOutput) DeepCopy() *EndpointRecordSetConversionOutput {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetConversionZone) DeepCopyInto(out *EndpointRecordSetConversionZone) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetConversionZone.
func (in *EndpointRecordSetConversionZone) DeepCopy() *EndpointRecordSetConversionZone {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetConversionZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetGeneratedRecordSetStatus) DeepCopyInto(out *EndpointRecordSetGeneratedRecordSetStatus) {
	*out = *in
	out.Ref = in.Ref
	if in.Fragment != nil {
		in, out := &in.Fragment, &out.Fragment
		*out = new(RecordSetSpecFragment)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetGeneratedRecordSetStatus.
func (in *EndpointRecordSetGeneratedRecordSetStatus) DeepCopy() *EndpointRecordSetGeneratedRecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetGeneratedRecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetHostnameStatus) DeepCopyInto(out *EndpointRecordSetHostnameStatus) {
	*out = *in
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(EndpointRecordSetZoneStatus)
		**out = **in
	}
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]EndpointRecordSetGeneratedRecordSetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetHostnameStatus.
func (in *EndpointRecordSetHostnameStatus) DeepCopy() *EndpointRecordSetHostnameStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetHostnameStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetList) DeepCopyInto(out *EndpointRecordSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetList.
func (in *EndpointRecordSetList) DeepCopy() *EndpointRecordSetList {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointRecordSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetSpec) DeepCopyInto(out *EndpointRecordSetSpec) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]EndpointTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetSpec.
func (in *EndpointRecordSetSpec) DeepCopy() *EndpointRecordSetSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetStatus) DeepCopyInto(out *EndpointRecordSetStatus) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]EndpointRecordSetHostnameStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetStatus.
func (in *EndpointRecordSetStatus) DeepCopy() *EndpointRecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRecordSetZoneStatus) DeepCopyInto(out *EndpointRecordSetZoneStatus) {
	*out = *in
	out.Ref = in.Ref
	out.Provider = in.Provider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRecordSetZoneStatus.
func (in *EndpointRecordSetZoneStatus) DeepCopy() *EndpointRecordSetZoneStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointRecordSetZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointTarget) DeepCopyInto(out *EndpointTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointTarget.
func (in *EndpointTarget) DeepCopy() *EndpointTarget {
	if in == nil {
		return nil
	}
	out := new(EndpointTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetSpecFragment) DeepCopyInto(out *RecordSetSpecFragment) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.A != nil {
		in, out := &in.A, &out.A
		*out = new(dnsv1alpha1.ARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.AAAA != nil {
		in, out := &in.AAAA, &out.AAAA
		*out = new(dnsv1alpha1.AAAARecordSet)
		(*in).DeepCopyInto(*out)
	}
	if in.CNAME != nil {
		in, out := &in.CNAME, &out.CNAME
		*out = new(dnsv1alpha1.CNAMERecordSet)
		**out = **in
	}
	in.Options.DeepCopyInto(&out.Options)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetSpecFragment.
func (in *RecordSetSpecFragment) DeepCopy() *RecordSetSpecFragment {
	if in == nil {
		return nil
	}
	out := new(RecordSetSpecFragment)
	in.DeepCopyInto(out)
	return out
}
